name: airq
channels:
  - defaults
dependencies:
  - python=3.13.2
  - pip
  - pip:
      - pycryptodome==3.23.0
      - python-dotenv==1.1.0
      - fastapi==0.115.12
      - uvicorn==0.34.2
      - sqlalchemy==2.0.41
      - psycopg2-binary==2.9.10
      - pydantic==2.11.4
      - pydantic-settings==2.2.1
      - asyncpg==0.30.0
      - httpx==0.28.1
      - prometheus_client==0.21.1