name: airq
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.2
  - pip
  - uv
  - pip:
      - pycryptodome==3.23.0
      - python-dotenv==1.1.0
      - fastapi==0.115.12
      - uvicorn==0.34.2
      - sqlalchemy==2.0.41
      - psycopg2-binary==2.9.10
      - pydantic==2.11.4
      - pydantic-settings==2.5.2
      - asyncpg==0.30.0
      - httpx==0.28.1
      - prometheus_client==0.21.1
      - mcp[cli]==1.9.4
      - reportlab==4.4.2
      - numpy==2.3.1
      - matplotlib==3.10.3
      - svglib==1.5.1